# Generated by Django 2.0.3 on 2018-04-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=64)),
                ('interface_method', models.CharField(max_length=8)),
                ('interface_desc', models.CharField(max_length=64)),
                ('interface_address', models.CharField(max_length=64)),
                ('interface_param', models.CharField(max_length=128)),
                ('interface_format', models.CharField(max_length=8)),
            ],
        ),
    ]
